Adding definition of question settings, updating license description …
grasple/open-format pull request #4
Opened 2023-03-28 14:11 UTC by Graspleric

This updates the format with two fixes:

- we updated the type of the license description to rich content as it can contain links
- we added the `settings` property to questions to facilitate the export of newly added settings

2023-03-29 15:13 UTC, screambeard commented on exercise.schema.json
> +          "type": "array",
@Graspleric i don't think this is an array. The index is important and does not start at zero. It starts at 1 and in theory you could have an entry like:
```
attempt_settings: {
 1:  { "percentage_of_full_points": 100},
 3:  { "percentage_of_full_points": 25},
}
```

2023-03-29 15:14 UTC, screambeard requested changes
The question_settings.attempt_settings is not an array. See my comment

2023-03-31 09:47 UTC, Graspleric commented
ah check, it is an object with numeric properties. I have updated the schema to reflect this.

2023-04-12 13:10 UTC, screambeard requested changes

2023-04-12 13:10 UTC, screambeard commented on exercise.schema.json
> +                "default": 0
@Graspleric maybe not the best implementation, but it starts at 1 not zero. Zo patternProperties should be [1-9] and default should be 1.

2023-04-13 08:06 UTC, Graspleric commented on exercise.schema.json
> +                "default": 0
@screambeard Check, I have updated the specification to start at 1 and updated the description to explain this as well. 

The default for the `percentage_of_full_points` should be 0 for all attempts except the first one, correct? That is way the default is 0 on this line, but the default for the `attempt_settings` object has 100 on line 109 below.

2023-04-13 08:40 UTC, screambeard approved these changes

2023-04-13 09:22 UTC, merged